export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const AGREGAR_TAREA_EXITO = "AGREGAR_TAREA_EXITO";
export const AGREGAR_TAREA_ERROR = "AGREGAR_TAREA_ERROR";

export const COMENZAR_DESCARGA_TAREAS = "COMENZAR_DESCARGA_TAREAS";
export const DESCARGA_TAREAS_ERROR = "DESCARGA_TAREAS_ERROR";
export const DESCARGA_TAREAS_EXITO = "DESCARGA_TAREAS_EXITO";

export const OBTENER_TAREA_ELIMINAR = "OBTENER_TAREA_ELIMINAR";
export const TAREA_ELIMINADO_EXITO = "TAREA_ELIMINADO_EXITO";
export const TAREA_ELIMINADO_ERROR = "TAREA_ELIMINADO_ERROR";

export const OBTENER_TAREA_EDITAR = "OBTENER_TAREA_EDITAR";
export const TAREA_EDITADO_EXITO = "TAREA_EDITADO_EXITO";
export const TAREA_EDITADO_ERROR = "TAREA_EDITADO_ERROR";
export const COMENZAR_EDICION_TAREA = "COMENZAR_EDICION_TAREA";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
